
development:
  adapter: postgresql
  encoding: unicode
  database: secret_sauce_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: secret_sauce_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: secret_sauce_production
  pool: 5
